### ISSUE TITLE
Use NuGet to pull in external dependencies

### ISSUE THREAD

**Issue by gtrog** [legendary-code/process-domain#1]
This was transferred from SVN, which used to use 'externals' for external libraries.  We should use NuGet or something similar instead.

**Comment by vivekrathod** [comment]
how can the dependence on Svn for versioning be removed? currently the rev part of the version comes the svn rev of last commit

**Comment by gtrog** [comment]
If we're using the latest commit, we should probably be tying it to specific versions of NUnit and log4net and then use NuGet dependencies to reference them:

https://docs.nuget.org/create/nuspec-reference

https://www.nuget.org/packages/log4net/
https://www.nuget.org/packages/NUnit

I'm not sure how this works, if you can just add the NuGet references and Visual Studio and whether build.cmd will then handle it properly, but it should be possible.

**Comment by vivekrathod** [comment]
I'm new to git so I've some basic questions - first of which is how do I create a CR for you - fork the repo and create a pull request? 
Also, I've made changes as below
1. using Nuget to manage log4net and NUnit dependency 
2. I upgraded the VS solution to VS 2013 but kept the target framework for all projects as .NET 2.0
3. fixed some build errors related to missing 'Version' dir under 'src' needed to create 'GlobalAssemblyInfo.cs'
4. Removed the dependence on SVN - this currently causes the 'build' to be left at 0 - major and minor are currently set manually at 1 and 9 resp

**Comment by gtrog** [comment]
Since you're a committer, you can simply create a branch and push to it.

So let's say you've made your changes on master, but haven't committed them yet:

> git branch fix_externals
> git checkout fix_externals
> git commit -am "some commit message"
> git push -u origin fix_externals

The '-am' will **a**dd files and specify a commit **m**essage, otherwise you have to separately add with 'git add [files]'

Once you have pushed to the branch, go to github and it should show you a button to create a pull request from the newly pushed branch.

**Comment by vivekrathod** [comment]
ok great, thanks

**Comment by gtrog** [comment]
Resolved in pull request #2
